[package]
name = "env-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
age.workspace = true
base64 = "0.22"
blake3.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
walkdir.workspace = true
zeroize.workspace = true
zip.workspace = true

[dev-dependencies]
env-test-support = { path = "../env-test-support" }
proptest.workspace = true
