export const en = {
  title: "Kavranta — One edit. Every file you choose.",
  description:
    "Manage the env files your project already uses. Find missing values, link selected variables, and let supported AI agents work through a redacted local broker.",
  skip: "Skip to content",
  home: "Kavranta home",
  navigation: "Main navigation",
  try: "Try it",
  features: "Why Kavranta",
  guide: "Get started",
  download: "Download",
  hero: ["One edit.", "Every file you choose."],
  heroBody:
    "Find the right variable. See exactly which files will change. Save once—and keep using your existing dev commands.",
  heroCta: "Try with sample files",
  heroSecondary: "Get the desktop app",
  heroNote: ["macOS & Windows", "Free · MIT", "No account required"],
  tools: "Works alongside your existing tools.",
  featureEyebrow: "FEWER FILES TO HUNT THROUGH.",
  featureTitle: ["Small tasks.", "Less repetition."],
  featureBody:
    "Start with the files you already have. Add links or an AI connection when you need them.",
  cards: [
    {
      title: "Find it. Fill it. Get back to work.",
      body: "See missing values across a project, find variables by name, and open the file that needs your attention.",
    },
    {
      title: "Choose the files that share a value.",
      body: "Link selected same-name variables inside one project. Review every affected file before saving. Other occurrences remain independent.",
    },
    {
      title: "Give an agent a task, not a pasted secret.",
      body: "Supported agents can inspect names, reuse protected values, and push selected variables through the local broker. The receiving tool or provider gets the value; normal agent responses do not.",
    },
  ],
  localEyebrow: "AT HOME IN YOUR PROJECT.",
  localTitle: ["Your files stay yours.", "So does your workflow."],
  localBody:
    "Keep your comments, file layout, and command for starting the app. Local editing does not need a hosted account.",
  security: "Read the security model",
  facts: [
    {
      title: "Edit existing files",
      body: "Requested edits preserve unrelated comments, ordering, and formatting.",
    },
    {
      title: "Share a selected setup",
      body: "Export an encrypted package and review conflicts before a teammate applies it.",
    },
    {
      title: "See Git risks",
      body: "Distinguish missing ignore rules, tracked files, and paths in Git history.",
    },
  ],
  guideEyebrow: "YOUR FIRST USEFUL TASK.",
  guideTitle: "Start with one project.",
  fullGuide: "Read the full guide",
  steps: [
    {
      title: "Install and choose a folder.",
      body: "Add the project you already work on. Registration discovers supported files without changing them.",
      hint: "Choose folder → Project overview",
    },
    {
      title: "Finish one missing value.",
      body: "Open a file, use Missing values only, enter a replacement, and Save. If your files are complete, review one existing variable.",
      hint: "Open file → Missing values only → Save",
    },
    {
      title: "Connect an AI tool when useful.",
      body: "Install a connection from the app, check its reported protection, then start a new agent session. The desktop works without this step.",
      hint: "“Inspect this project's env structure without reading values.”",
    },
  ],
  faqTitle: "Before you install.",
  faqs: [
    {
      question: "Where do my values live?",
      answer:
        "In the env files your project already uses. Project metadata stores policy and links, not values. Local editing works offline; update checks and explicitly requested provider operations have separate network paths.",
    },
    {
      question: "Does this stop every possible AI secret leak?",
      answer:
        "The Kavranta broker blocks protected-value reads. Direct-file defenses depend on the connected host's permissions and guards. Plaintext files remain accessible to other processes with filesystem permission; Kavranta does not isolate a compromised operating system.",
    },
    {
      question: "Are links and deployments automatic sync?",
      answer:
        "Only explicitly linked variables in the same project change together on Save. Provider push is a requested, one-way operation. GitHub Secrets cannot be read back, so a successful push does not prove current equality.",
    },
    {
      question: "Which computers are supported?",
      answer:
        "macOS Apple Silicon and Intel, plus Windows 10/11 x64. macOS apps are Developer ID signed and notarized. Windows is currently an unsigned beta: SmartScreen may warn, and organization policy may block installation. Linux is not yet supported.",
    },
  ],
  downloadEyebrow: "TRY IT ON YOUR OWN PROJECT.",
  downloadTitle: ["One folder.", "A clearer setup."],
  downloadBody:
    "Choose an installer from the official GitHub release, or use Homebrew on macOS.",
  mac: "macOS installers",
  windows: "Windows unsigned beta",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Select the command to copy",
  copyLabel: "Copy Homebrew install command",
  downloadNote:
    "macOS: choose aarch64 for Apple Silicon, x64 for Intel. Windows: choose x64-setup.exe. No Rust toolchain is needed.",
  footer: "Built for the files you already use.",
  roadmap: "Roadmap",
  feedback: "Share feedback",
  playground: {
    eyebrow: "TRY IT BEFORE YOU INSTALL.",
    title: "Which files should change?",
    body: "Select a file to share Local's AUTH_SECRET. Preview the impact, then save a sample update.",
    label: "Hands-on linking demo",
    source: "Source · Local",
    choose: "Link with Local",
    independent: "Independent unless you select it",
    production:
      "Production is a separate choice. Select it only if it should share this value.",
    unchanged: "Unchanged",
    revision: "Demo update",
    preview: "Preview affected files",
    apply: "Save sample update",
    reset: "Reset demo",
    review: "Only these files will change:",
    saved: "Sample update saved to",
    files: "files",
    ready: "Choose at least one file to preview the link.",
    disclosure:
      "Illustration with fixed masks. No real values, filesystem access, or provider requests. Real links compare values in Rust and require a source choice when values conflict.",
  },
  demo: {
    label: "Illustrated agent workflow",
    scenarios: "Demo scenarios",
    pause: "Pause demo",
    play: "Play demo",
    replay: "Replay demo from start",
    seal: ["Ask naturally.", "See the impact."],
    disclosure: [
      "Illustrated with synthetic data.",
      "No real file changes or external requests.",
    ],
    transcript: "Read the demo transcript",
    request: "Request",
    result: "Result",
    appLabel: "Application preview",
    localProject: "Local project",
    overview: "Project overview",
    connections: "AI connections",
    activity: "AI activity",
    connected: "AI tool connected",
    variables: "variables",
    groups: "groups",
    add: "+ New variable",
    all: "All variables",
    linked: "Linked",
    missing: "Missing",
    appName: "Application name",
    mode: "Runtime environment",
    database: "Database connection",
    secret: "Authentication signing secret",
    allowed: "AI allowed",
    protected: "Protected",
    required: "Needs a value",
    twoLinked: "Linked in 2 files",
    pushed: "1 Secret sent to GitHub staging",
    twoSaved: "Saved to 2 files",
    saved: "Changes saved",
    working: "Applying the requested task",
    idle: "All changes saved",
    terminalConnected: "Kavranta connected",
    terminalTitle: "Keep your development flow.",
    terminalBody: "Ask for an environment task in your own words.",
    terminalNote: "Protected values stay out of normal responses",
    done: "Done",
    inProgress: "Working",
  },
};

export const ko: typeof en = {
  title: "Kavranta — 한 번의 편집, 직접 고른 파일에.",
  description:
    "쓰던 env 파일을 그대로 관리하세요. 빈 값 찾기, 변수 연결, 값 비노출 AI 작업까지 Kavranta에서 이어집니다.",
  skip: "본문으로 건너뛰기",
  home: "Kavranta 홈",
  navigation: "메인 메뉴",
  try: "직접 체험",
  features: "주요 기능",
  guide: "시작 가이드",
  download: "다운로드",
  hero: ["한 번의 편집,", "직접 고른 파일에."],
  heroBody:
    "필요한 변수를 찾고, 바뀔 파일을 확인하고, 한 번에 저장하세요. 개발 서버를 켜는 명령은 쓰던 그대로입니다.",
  heroCta: "샘플 파일로 직접 체험",
  heroSecondary: "데스크톱 앱 받기",
  heroNote: ["macOS & Windows", "무료 · MIT", "가입 없이 시작"],
  tools: "지금 사용하는 도구와 함께.",
  featureEyebrow: "찾는 시간은 줄이고.",
  featureTitle: ["작은 설정 작업을", "더 간단하게."],
  featureBody:
    "이미 있는 파일부터 시작하세요. 연결과 AI 연동은 필요할 때 더하면 됩니다.",
  cards: [
    {
      title: "찾고, 채우고, 개발을 이어가세요.",
      body: "프로젝트의 빈 값을 확인하고 변수명으로 검색해 필요한 파일을 바로 여세요.",
    },
    {
      title: "같이 쓸 값만 직접 연결하세요.",
      body: "한 프로젝트 안에서 같은 이름의 변수를 골라 연결합니다. 저장할 파일을 먼저 확인하며 다른 항목은 독립적으로 유지됩니다.",
    },
    {
      title: "AI에겐 비밀 대신 할 일을 알려주세요.",
      body: "지원 에이전트는 로컬 Broker로 이름 조회, 보호된 값 재사용, 선택한 변수 배포를 수행합니다. 값을 받는 곳은 대상 도구나 Provider이며 일반 에이전트 응답에는 반환되지 않습니다.",
    },
  ],
  localEyebrow: "프로젝트의 원래 자리에서.",
  localTitle: ["파일은 원래 자리에.", "주도권은 당신에게."],
  localBody:
    "주석, 파일 배치, 개발 명령을 그대로 유지합니다. 로컬 편집을 위해 온라인 계정을 만들 필요가 없습니다.",
  security: "보안 모델 읽기",
  facts: [
    {
      title: "기존 파일 그대로 편집",
      body: "요청한 부분을 편집하고 나머지 주석, 순서, 형식을 보존합니다.",
    },
    {
      title: "필요한 설정만 팀에 전달",
      body: "암호화 패키지로 내보내고, 팀원은 충돌을 확인한 뒤 적용합니다.",
    },
    {
      title: "Git 위험을 구분해서 확인",
      body: "ignore 누락, 추적 중인 파일, Git 기록에 남은 경로를 알려줍니다.",
    },
  ],
  guideEyebrow: "첫 번째 유용한 작업.",
  guideTitle: "프로젝트 하나로 시작하세요.",
  fullGuide: "전체 가이드 읽기",
  steps: [
    {
      title: "설치하고 폴더를 고르세요.",
      body: "작업 중인 프로젝트를 등록하세요. 등록 과정은 지원 파일을 찾으며 내용을 변경하지 않습니다.",
      hint: "폴더 선택 → 프로젝트 개요",
    },
    {
      title: "빈 값 하나를 채워 보세요.",
      body: "파일에서 값 없음 필터를 켜고 입력한 뒤 저장하세요. 이미 다 채웠다면 기존 변수 하나를 살펴보세요.",
      hint: "파일 열기 → 값 없음 필터 → 저장",
    },
    {
      title: "필요할 때 AI를 연결하세요.",
      body: "앱에서 연결을 설치하고 보호 상태를 확인한 뒤 새 에이전트 세션을 여세요. AI 없이도 데스크톱 앱을 쓸 수 있습니다.",
      hint: "“이 프로젝트의 환경변수 구조를 값 없이 확인해줘.”",
    },
  ],
  faqTitle: "설치 전에 알아두세요.",
  faqs: [
    {
      question: "환경변수는 어디에 저장되나요?",
      answer:
        "프로젝트가 쓰던 env 파일에 남습니다. 프로젝트 메타데이터에는 정책과 연결 관계만 저장됩니다. 로컬 편집은 오프라인으로 가능하며 업데이트 확인과 명시적인 Provider 작업은 별도의 네트워크 경로를 사용합니다.",
    },
    {
      question: "모든 AI 비밀 유출을 막아 주나요?",
      answer:
        "Kavranta Broker는 보호된 값의 읽기를 차단합니다. 직접 파일 접근의 방어 수준은 연결한 도구의 권한 설정과 Guard에 따라 달라집니다. 파일 접근 권한이 있는 다른 프로세스나 손상된 운영체제까지 격리하지는 않습니다.",
    },
    {
      question: "연결과 배포는 자동으로 동기화되나요?",
      answer:
        "같은 프로젝트에서 직접 연결한 변수만 저장할 때 함께 변경됩니다. Provider 배포는 요청한 단방향 전송입니다. GitHub Secret은 다시 읽을 수 없어 현재 값의 일치를 보장하지 않습니다.",
    },
    {
      question: "어떤 컴퓨터에서 쓸 수 있나요?",
      answer:
        "macOS Apple Silicon·Intel과 Windows 10/11 x64를 지원합니다. macOS 앱은 Developer ID 서명과 공증을 거칩니다. Windows는 현재 미서명 베타로 SmartScreen 경고가 표시되거나 조직 정책에 따라 차단될 수 있습니다. Linux는 아직 지원하지 않습니다.",
    },
  ],
  downloadEyebrow: "이제 내 프로젝트에서.",
  downloadTitle: ["폴더 하나부터.", "설정은 더 명확하게."],
  downloadBody:
    "공식 GitHub 릴리스에서 설치 파일을 고르거나 macOS에서 Homebrew를 사용하세요.",
  mac: "macOS 설치 파일",
  windows: "Windows 미서명 베타",
  copy: "복사",
  copied: "복사됨",
  copyFailed: "명령어를 선택해 복사하세요",
  copyLabel: "Homebrew 설치 명령 복사",
  downloadNote:
    "macOS: Apple Silicon은 aarch64, Intel은 x64. Windows는 x64-setup.exe를 고르세요. Rust 설치는 필요 없습니다.",
  footer: "지금 쓰는 파일을 위한 도구.",
  roadmap: "로드맵",
  feedback: "사용 의견 남기기",
  playground: {
    eyebrow: "설치 전에 직접 써 보세요.",
    title: "어떤 파일을 함께 바꿀까요?",
    body: "Local의 AUTH_SECRET을 같이 쓸 파일을 고르세요. 영향 범위를 확인하고 샘플 변경을 저장해 보세요.",
    label: "파일 연결 직접 체험",
    source: "기준 파일 · Local",
    choose: "Local과 연결",
    independent: "선택하기 전에는 독립적으로 관리",
    production:
      "Production은 별도로 판단하세요. 같은 값을 써야 할 때만 선택하세요.",
    unchanged: "변경 없음",
    revision: "샘플 변경",
    preview: "바뀔 파일 확인",
    apply: "샘플 변경 저장",
    reset: "체험 초기화",
    review: "이 파일만 변경됩니다:",
    saved: "샘플 변경 저장 완료 ·",
    files: "개 파일",
    ready: "연결할 파일을 하나 이상 선택하세요.",
    disclosure:
      "고정 마스크를 사용하는 설명용 체험입니다. 실제 값, 파일 접근, 외부 전송은 없습니다. 실제 연결은 Rust에서 값을 비교하고 충돌 시 기준 파일을 선택합니다.",
  },
  demo: {
    label: "에이전트 작업 흐름 예시",
    scenarios: "데모 시나리오",
    pause: "데모 일시정지",
    play: "데모 재생",
    replay: "데모 처음부터 재생",
    seal: ["요청은 자연스럽게.", "반영은 정확하게."],
    disclosure: [
      "합성 데이터로 재현한 데모입니다.",
      "실제 파일 변경이나 외부 전송은 없습니다.",
    ],
    transcript: "데모를 텍스트로 읽기",
    request: "요청",
    result: "결과",
    appLabel: "앱 반영 미리보기",
    localProject: "로컬 프로젝트",
    overview: "프로젝트 개요",
    connections: "AI 도구 연결",
    activity: "AI 활동",
    connected: "AI 도구 연결됨",
    variables: "개 변수",
    groups: "개 그룹",
    add: "+ 새 변수",
    all: "전체 변수",
    linked: "연결됨",
    missing: "값 없음",
    appName: "애플리케이션 이름",
    mode: "실행 환경",
    database: "데이터베이스 연결",
    secret: "인증 서명용 비밀값",
    allowed: "AI 허용",
    protected: "보호됨",
    required: "설정 필요",
    twoLinked: "2개 파일에 연결됨",
    pushed: "GitHub staging에 Secret 1개 전송 완료",
    twoSaved: "2개 파일에 반영되었습니다",
    saved: "변경사항이 저장되었습니다",
    working: "AI 작업을 반영하고 있습니다",
    idle: "모든 변경사항이 저장되었습니다",
    terminalConnected: "Kavranta 연결됨",
    terminalTitle: "개발 흐름을 이어가세요.",
    terminalBody: "환경변수 작업을 자연스럽게 요청하세요.",
    terminalNote: "보호된 값은 일반 응답에 반환되지 않습니다",
    done: "완료",
    inProgress: "작업 중",
  },
};
